In [215]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:,.0f}'.format
food = pd.read_csv('식음매출.csv', index_col = 0)
sleep = pd.read_csv('숙박매출.csv', index_col = 0)
buy = pd.read_csv('소매매출.csv', index_col = 0)

In [217]:
#식음료
#매출액
food['창업비용']=89000000
food['매출ratio'] = food['점포당 매출액'] / food['창업비용']
food_1 = food.sort_values('매출ratio',ascending=False)
food_1.to_csv('식음료매출액.csv')
food_1.reset_index(inplace=True)
del food_1["index"]
food_1.reset_index(inplace=True)

#점포당이용자수
del food["창업비용"]
del food["매출ratio"]
food['점포당이용자수']=food['이용자수']/food['점포 수']
food_2 = food.sort_values('점포당이용자수',ascending=False)
food_2.to_csv('식음료점포당이용자수.csv')
food_2.reset_index(inplace=True)
del food_2["index"]
food_2.reset_index(inplace=True)

#동별이용자수
del food["점포당이용자수"]
food['총이용자수']=food['이용자수'].sum()
food['동별이용자수']=food['이용자수']/food['총이용자수'] * 100
food_3 = food.sort_values('동별이용자수',ascending=False)
food_3.to_csv('식음료동별이용자비율.csv')
food_3.reset_index(inplace=True)
del food_3["index"]
food_3.reset_index(inplace=True)

#점수구하기
foodtotal = pd.concat([food_1,food_2,food_3])
foodtotal=foodtotal[["index","읍면동명"]]
foodtotal["점수"]=pd.to_numeric(foodtotal["index"])
del foodtotal["index"]

#등수구하기
food1=foodtotal.groupby(["읍면동명"],as_index=False).sum()
food1["등수"]=food1["점수"].rank(method="dense",ascending=True)
food1=food1.sort_values("등수",ascending=True)
food1

    읍면동명   점수  등수
15   송산동    3   1
36   천지동   10   2
32   정방동   10   2
35   중앙동   11   3
3    노형동   11   3
16   아라동   17   4
25  용담2동   20   5
28  이도2동   21   6
19    연동   26   7
22   오라동   30   8
31  일도2동   36   9
12   삼양동   42  10
0    건입동   43  11
21   예래동   49  12
8    동홍동   53  13
18   애월읍   55  14
34   중문동   58  15
23   외도동   58  15
20   영천동   59  16
41   화북동   60  17
6    대천동   62  18
33   조천읍   65  19
11  삼도2동   66  20
13   서홍동   67  21
4    대륜동   71  22
5    대정읍   71  22
14   성산읍   72  23
7    도두동   77  24
40   한림읍   77  24
17   안덕면   81  25
30  일도1동   84  26
1    구좌읍   88  27
9    봉개동   93  28
42   효돈동   94  29
29   이호동   97  30
10  삼도1동   98  31
27  이도1동  102  32
38   표선면  102  32
24  용담1동  106  33
2    남원읍  108  34
39   한경면  114  35
26   우도면  117  36
37   추자면  125  37

In [218]:
#숙박업
#매출액구하기
sleep['창업비용']=417000000
sleep['매출ratio'] = sleep['점포당 매출액'] / sleep['창업비용']
sleep_1 = sleep.sort_values('매출ratio',ascending=False)
sleep_1.to_csv('숙박매출액.csv')
sleep_1.reset_index(inplace=True)
del sleep_1["index"]
sleep_1.reset_index(inplace=True)

#점포당이용자수구하기
del sleep["창업비용"]
del sleep["매출ratio"]
sleep['점포당이용자수']=sleep['이용자수']/sleep['점포 수']
sleep_2 = sleep.sort_values('점포당이용자수',ascending=False)
sleep_2.to_csv('숙박점포당이용자수.csv')
sleep_2.reset_index(inplace=True)
del sleep_2["index"]
sleep_2.reset_index(inplace=True)


#동별이용자수구하기
del sleep["점포당이용자수"]
sleep['총이용자수']=sleep['이용자수'].sum()
sleep['동별이용자수']=sleep['이용자수']/sleep['총이용자수'] * 100
sleep_3 = sleep.sort_values('동별이용자수',ascending=False)
sleep_3.to_csv('숙박동별이용자비율.csv')
sleep_3.reset_index(inplace=True)
del sleep_3["index"]
sleep_3.reset_index(inplace=True)


#점수구하기
sleeptotal = pd.concat([sleep_1,sleep_2,sleep_3])
sleeptotal=sleeptotal[["index","읍면동명"]]
sleeptotal["점수"]=pd.to_numeric(sleeptotal["index"])
del sleeptotal["index"]

#등수구하기
sleep1=sleeptotal.groupby(["읍면동명"],as_index=False).sum()
sleep1["등수"]=sleep1["점수"].rank(method="dense",ascending=True)
sleep1=sleep1.sort_values("등수",ascending=True)
sleep1

    읍면동명   점수  등수
21   예래동    3   1
35   중앙동    6   2
19    연동    8   3
32   정방동   15   4
15   송산동   17   5
11  삼도2동   23   6
20   영천동   24   7
36   천지동   26   8
34   중문동   28   9
16   아라동   29  10
0    건입동   29  10
6    대천동   29  10
4    대륜동   38  11
23   외도동   39  12
18   애월읍   41  13
3    노형동   42  14
14   성산읍   43  15
28  이도2동   47  16
27  이도1동   53  17
33   조천읍   62  18
10  삼도1동   62  18
40   한림읍   63  19
13   서홍동   64  20
22   오라동   74  21
25  용담2동   81  22
2    남원읍   81  22
7    도두동   81  22
5    대정읍   82  23
8    동홍동   82  23
12   삼양동   82  23
38   표선면   86  24
17   안덕면   89  25
30  일도1동   91  26
29   이호동   92  27
1    구좌읍   96  28
37   추자면   99  29
24  용담1동  103  30
31  일도2동  107  31
9    봉개동  111  32
26   우도면  114  33
39   한경면  120  34
42   효돈동  121  35
41   화북동  126  36

In [219]:
#소매
#매출액구하기
buy['창업비용']=92000000
buy['매출ratio'] = buy['점포당 매출액'] / buy['창업비용']
buy_1 = buy.sort_values('매출ratio',ascending=False)
buy_1.to_csv("소매매출액.csv")
buy_1.reset_index(inplace=True)
del buy_1["index"]
buy_1.reset_index(inplace=True)

#점포당이용자수구하기
del buy["창업비용"]
del buy["매출ratio"]
buy['점포당이용자수']=buy['이용자수']/buy['점포 수']
buy_2 = buy.sort_values('점포당이용자수',ascending=False)
buy_2.to_csv('소매점포당이용자수.csv')
buy_2.reset_index(inplace=True)
del buy_2["index"]
buy_2.reset_index(inplace=True)

#동별이용자수구하기
del buy["점포당이용자수"]
buy['총이용자수']=buy['이용자수'].sum()
buy['동별이용자수']=buy['이용자수']/buy['총이용자수'] * 100
buy_3 = buy.sort_values('동별이용자수',ascending=False)
buy_3.to_csv('소매동별이용자비율.csv')
buy_3.reset_index(inplace=True)
del buy_3["index"]
buy_3.reset_index(inplace=True)

#점수구하기
buytotal = pd.concat([buy_1,buy_2,buy_3])
buytotal=buytotal[["index","읍면동명"]]
buytotal["점수"]=pd.to_numeric(buytotal["index"])
del buytotal["index"]

#등수구하기
buy1=buytotal.groupby(["읍면동명"],as_index=False).sum()
buy1["등수"]=buy1["점수"].rank(method="dense",ascending=True)
buy1=buy1.sort_values("등수",ascending=True)
buy1

    읍면동명   점수  등수
15   송산동    1   1
32   정방동    3   2
36   천지동    5   3
35   중앙동    9   4
3    노형동   15   5
28  이도2동   16   6
25  용담2동   23   7
23   외도동   28   8
41   화북동   37   9
30  일도1동   37   9
12   삼양동   37   9
16   아라동   39  10
33   조천읍   41  11
31  일도2동   43  12
19    연동   45  13
0    건입동   48  14
10  삼도1동   51  15
8    동홍동   54  16
24  용담1동   57  17
5    대정읍   62  18
4    대륜동   62  18
14   성산읍   63  19
27  이도1동   68  20
22   오라동   71  21
7    도두동   72  22
40   한림읍   73  23
18   애월읍   76  24
26   우도면   82  25
21   예래동   83  26
6    대천동   83  26
38   표선면   85  27
11  삼도2동   87  28
29   이호동   90  29
34   중문동   92  30
9    봉개동   97  31
2    남원읍  102  32
20   영천동  104  33
17   안덕면  105  34
37   추자면  109  35
13   서홍동  110  36
42   효돈동  110  36
1    구좌읍  113  37
39   한경면  121  38

In [ ]:
#문화레저